//to run socket program we first have to chack that it is working or not 

run:	
	gcc myFirst_socket.c
	./a.out
//on the other terminal we have to run following comand to execute client
	netstat -atp 
	telnet localhost 10000
